name: Build Vue
on: 
  push:
    branches: [ "website-test" ]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'CCooley33'
        reponame: 'Travel-Companion'
        token: ${{ secrets.GITHUB_TOKEN }}
